### PR TITLE
add Duration and DurationP

### PR DESCRIPTION
**Pull request by xh3b4sd**
I played around with the upstream controller runtime and thought this could come handy in the future.

### CODE REVIEW

**Review by MarcelMue — APPROVED** [review]

**Review by tuommaki — APPROVED** [review]

**Comment by kopiczko** [comment]
Why is it useful? You can use `*d` to dereference it. This library should be only used for primitive types IMO.

**Comment by xh3b4sd** [comment]
When you can just dereference the other methods are useless as well. I just follow the pattern that was there. This is generally useful when working with certain k8s deps because everything has to be a pointer and when you want to configure a duration you need to do weird stuff in your code, which this library now simply provides. I found that being a useful idea.

**Comment by kopiczko** [comment]
> When you can just dereference the other methods are useless as well.

No you can't do `&1` or `&"a"`.

**Comment by xh3b4sd** [comment]
You can also not do `&(1*time.Minute)`.

**Comment by kopiczko** [comment]
> You can also not do `&(1*time.Minute)`.

Now we're talking. I didn't realize that. That's cool I like it :D

**Pull request merged**
